### ISSUE TITLE
FOF Follow Tags

### ISSUE THREAD

**Issue by TB54** [FreeFlarum/freeflarum.com#363] opened 2022-05-23 08:48 UTC
__Packagist URL for extension:__
https://packagist.org/packages/fof/follow-tags

__Why should we install the extension?__
Well, i just think it's very useful, specially for the capacity to hide topics which doesn't interest you from all discussion!

---
> ###### **Note**: This issue requires at least 5 upvotes (👍) before it can be added to FreeFlarum.
---

**Comment by CWKevo** [comment] 2022-09-16 15:37
Duplicate of #83

**Closed by CWKevo** 2022-09-16 15:37 UTC
Labels: 🙋 Extension/feature request
