### ISSUE TITLE
I would like to have more customization options for my forum

### ISSUE THREAD

**Issue by AgustinPrS** [FreeFlarum/freeflarum.com#451] opened 2023-10-14 22:33 UTC
### Extension URL

https://github.com/the-turk/flarum-pallet-theme

### Why should we install this extension?

The original post on this topic is: https://discuss.flarum.org/d/27757-pallet-theme
It basically shows what this theme looks like within Flarum, it is a very good theme, I hope you can enjoy it.

**Comment by SKevo18** [comment] 2023-11-13 17:42
This extension is unfortunately marked as incompatible, and cannot be included at FreeFlarum, sorry. Duplicate of #266

**Closed** 2023-11-13 17:43 UTC
Labels: 📄📄  Duplicate, 🙋 Extension/feature request
