### ISSUE TITLE
Iframe extension for free flarum

### ISSUE THREAD

**Issue by mdsafinahmedrudra** [FreeFlarum/freeflarum.com#386] opened 2022-08-24 14:28 UTC
__Packagist URL:__ https://packagist.org/packages/zerosonesfun/flarum-bbcode-iframe

__Why should this extension be installed:__
I need a extension for embeding website into my free flarum forum posts. Ii will be great if you add an extension for that reason. So that, I as well as other people who use free flarum can embed websites into their free flarum posts.

Thank you

> ---
> This extension requires at least 5 👍 to be honored.
> 
> ---

**Comment by CWKevo** [comment] 2022-08-24 14:31
Please, follow the issue template. If an extension like this already exists, feel free to share a link to it and I will include it. If it doesn't exist yet, then please note that FreeFlarum does not create extensions on request, and you will need to wait for someone else to create it.

**Comment by mdsafinahmedrudra** [comment] 2022-08-26 18:00
I am so sorry for the late reply .
Can you please add these two urls? 
And then can I embed them into free flarum?
https://10min-ssc22-final-prep.on.drv.tw/www.pokemongm.com/
https://10min-ssc22-final-prep.on.drv.tw/www.pkmngame.com/

**Comment by CWKevo** [comment] 2022-08-26 18:06
So if I understand it correctly, you would like to install the iFrame extension that I have mentioned above to FreeFlarum so that you may create an embed of the two URLs that you have mentioned, correct?

If that's the case, I'm editing your first comment to be a valid extension request. Please, follow the template next time

**Comment by mdsafinahmedrudra** [comment] 2022-08-26 18:18
yes you are right. I want to add them on my free flarum post. ok, I will. SO sorry for that :(

**Comment by Profi420** [comment] 2022-12-04 21:10
Same like here?
https://github.com/FreeFlarum/freeflarum.com/issues/404

**Comment by CWKevo** [comment] 2022-12-05 03:12
Duplicate of #404, installed

**Closed** 2022-12-05 03:13 UTC
Labels: 📄📄  Duplicate, 🙋 Extension/feature request
